language: node_js
node_js: '14'

before_script:
- npm install firebase-tools -g
- npm install
- npm run test

deploy:
  - provider: script
    script: firebase use $FB_PROJECT_ID && firebase deploy --only functions
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(main|dev)$