language: node_js
node_js: '14'

before_script:
- npm install firebase-tools -g
- npm install
- npm run test

script:
- firebase use $FB_PROJECT_NAME
- firebase deploy --only functions

branches:
  only:
    - main
    - dev
