version: "3.8"
services:
    api:
        build:
            context: .
        ports:
            - "4000:4000"
            - "5001:5001"
            - "4400:4400"
            - "4500:4500"
        volumes:
            - ./lib:/app/lib